version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    econtainer_name: chat_frontend
    ports:
      - 8080:8080
    volumes:
      - .:/app
    stdin_open: true
    tty: true
networks:
  default:
    name: chat_network